# Migrations Dockerfile
FROM alpine:3.19

# Download goose binary
RUN apk add --no-cache wget \
    && wget -q https://github.com/pressly/goose/releases/download/v3.26.0/goose_linux_x86_64 -O /usr/local/bin/goose \
    && chmod +x /usr/local/bin/goose \
    && apk del wget

WORKDIR /migrations
COPY migrations/*.sql ./

CMD ["sh", "-c", "goose postgres \"$GOOSE_DBSTRING\" up"]
