# Migrations Dockerfile
FROM golang:1.24-alpine AS builder

RUN go install github.com/pressly/goose/v3/cmd/goose@latest

FROM alpine:3.19

COPY --from=builder /go/bin/goose /usr/local/bin/goose

WORKDIR /migrations
COPY migrations/*.sql ./

CMD ["sh", "-c", "goose postgres \"$GOOSE_DBSTRING\" up"]
