// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notes.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countNotes = `-- name: CountNotes :one
SELECT COUNT(*) FROM notes
`

func (q *Queries) CountNotes(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countNotes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNote = `-- name: CreateNote :exec
INSERT INTO notes (id, content, created_at, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateNoteParams struct {
	ID        string             `json:"id"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) error {
	_, err := q.db.Exec(ctx, createNote,
		arg.ID,
		arg.Content,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredNotes = `-- name: DeleteExpiredNotes :execrows
DELETE FROM notes WHERE expires_at <= NOW()
`

func (q *Queries) DeleteExpiredNotes(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredNotes)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteNote = `-- name: DeleteNote :exec
DELETE FROM notes WHERE id = $1
`

func (q *Queries) DeleteNote(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteNote, id)
	return err
}

const getNoteByID = `-- name: GetNoteByID :one
SELECT id, content, created_at, expires_at
FROM notes
WHERE id = $1 AND expires_at > NOW()
`

func (q *Queries) GetNoteByID(ctx context.Context, id string) (*Note, error) {
	row := q.db.QueryRow(ctx, getNoteByID, id)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return &i, err
}
